### ISSUE TITLE
Terminal.app colors don't look the same

### ISSUE THREAD

**Issue by dvisztempacct** [aradunovic/perun.vim#1]
[Take a look](https://i.imgur.com/Gu1vDLJ.png)

**Comment by aradunovic** [comment]
Thank you very much for reporting this.
I can confirm that colors don't look the same, not only for Terminal.app, but for (some) other terminals as well. 
Will try to fix it ASAP.

**Comment by aradunovic** [comment]
fd01fafa16db9389694c1f0c1e4c88e7e97ef3e8 should fix wrong terminal colors

@dvisztempacct could you confirm?

**Comment by dvisztempacct** [comment]
@aradunovic [here is the new one](https://i.imgur.com/48DvlZx.png)

I'm unsure if the difference now might have to do with the way my vim is highlighting .vim files...

I'm using neovim btw!

**Comment by aradunovic** [comment]
Oh, I misunderstood you. In order to use this colorscheme you need terminal that supports "true color". AFAIK, Terminal.app does not support true color yet. You should try [iTerm](https://www.iterm2.com/) instead.

You can find more info [here](https://github.com/neovim/neovim/wiki/FAQ#how-can-i-use-true-color-in-the-terminal)

**Comment by dvisztempacct** [comment]
I thought it did... I'll have to mess around with it more later.

Thanks!

**Comment by dvisztempacct** [comment]
Okay I downloaded iTerm2 and imported [perun.itermcolors](https://github.com/aradunovic/perun.vim/blob/master/terminal/iterm/perun.itermcolors) and `set termguicolors` in my `~/.config/nvim/init.vim` and [here is the latest image](https://imgur.com/c8716dd0-a908-4a7b-ae58-5345e931d7a5).

Am I missing something?

Thanks!

**Comment by aradunovic** [comment]
Inage link is broken... I reopened the issue, so it would be great if you could post a comment with a screenshot and your init.vim settings.

Thanks!
